In [1]:
import tensorflow

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [14]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[-1, 3],
                 [4, 2]])

In [15]:
multiply = tf.matmul(a, b)

In [16]:
type(multiply)

tensorflow.python.framework.ops.Tensor

In [17]:
with tf.Session() as sess:
    print(sess.run(a), '\n')
    print(sess.run(b), '\n')
    print(sess.run(multiply))

[[1 2]
 [3 4]] 

[[-1  3]
 [ 4  2]] 

[[ 7  7]
 [13 17]]


In [18]:
multiply2 = tf.matmul(b, a)

In [19]:
with tf.Session() as sess:
    print(sess.run(multiply2))

[[ 8 10]
 [10 16]]


In [20]:
a1 = tf.constant([[2, 3], [0, 1], [-1, 4]])
b1 = tf.constant([[1, 2, 3], [-2, 0, 4]])
multiply3 = tf.matmul(a1, b1)

In [21]:
with tf.Session() as sess:
    print(sess.run(a1), '\n')
    print(sess.run(b1), '\n')
    print(sess.run(multiply3))

[[ 2  3]
 [ 0  1]
 [-1  4]] 

[[ 1  2  3]
 [-2  0  4]] 

[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
