In [1]:
import tensorflow

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
ph = tf.placeholder('float', None)

In [4]:
operation = ph + 2

In [5]:
arr = [1, 2, 3]

In [6]:
with tf.Session() as sess:
    result = sess.run(operation, feed_dict = {ph: arr})
    print(result)

[3. 4. 5.]


In [7]:
ph2 = tf.placeholder('float', [None, 5])
datas = [[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 10]]

In [8]:
operation2 = ph2 * 5

In [9]:
with tf.Session() as sess:
    result = sess.run(operation2, feed_dict = {ph2: datas})
    print(result)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
