In [1]:
import tensorflow

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
a = tf.constant([9, 8, 7], name = 'a')
b = tf.constant([1, 2, 3], name = 'b')

In [4]:
sums = a + b

In [6]:
type(a)

tensorflow.python.framework.ops.Tensor

In [8]:
print(a)

Tensor("a:0", shape=(3,), dtype=int32)


In [10]:
with tf.Session() as sess:
    print(sess.run(sums))

[10 10 10]


In [11]:
a1 = tf.constant([[1, 2, 3],
                  [4, 5, 6]], name = 'a1')

In [12]:
type(a1)

tensorflow.python.framework.ops.Tensor

In [13]:
print(a1)

Tensor("a1:0", shape=(2, 3), dtype=int32)


In [15]:
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [16]:
b1 = tf.constant([[1, 2, 3],
                  [4, 5, 6]], name = 'b1')

In [17]:
sums1 = tf.add(a1, b1)

In [20]:
with tf.Session() as sess:
    print(sess.run(a1), '\n')
    print(sess.run(b1), '\n')
    print(sess.run(sums1))

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]] 

[[ 2  4  6]
 [ 8 10 12]]


In [24]:
a2 = tf.constant([[1, 2, 3],
                  [4, 5, 6]], name = 'a2')
b2 = tf.constant([[1], [2]], name = 'b2')
sums2 = tf.add(a2, b2)

In [25]:
with tf.Session() as sess:
    print(sess.run(a2), '\n')
    print(sess.run(b2), '\n')
    print(sess.run(sums2))

[[1 2 3]
 [4 5 6]] 

[[1]
 [2]] 

[[2 3 4]
 [6 7 8]]
